* ERC
** command history
ERC, the Emacs IRC client, provides a command history feature that allows you to recall and reuse commands you have previously entered in the buffer. Here are the basic commands and key bindings for working with the command history:

- M-p and M-n: Move backward and forward in the command history, respectively. These keys are bound to comint-previous-input and comint-next-input by default.
- M-r: Search backward through the command history for a command matching the specified regular expression. This key is bound to comint-history-isearch-backward-regexp by default.
- M-s: Search forward through the command history for a command matching the specified regular expression. This key is bound to comint-history-isearch-forward-regexp by default.
- M-!: Execute the previous command in the command history. This key is bound to comint-previous-matching-input-from-input by default.
- C-c C-l: List the last 20 commands in the command history. This key is bound to comint-show-previous-input by default.

You can customize the number of commands saved in the history by setting the comint-input-ring-size variable in your Emacs configuration file (e.g. ~/.emacs). For example, to increase the history size to 1000, you can add the following line to your configuration file:

(setq comint-input-ring-size 1000)

Note that the command history is saved across ERC sessions, so you can recall commands you entered in previous sessions.

** Cheatsheet
while ! ollama run; do sleep 5; done

